
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckpgfjqinvxjlbbyiujh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrcGdmanFpbnZ4amxiYnlpdWpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNzc2NDksImV4cCI6MjA2MTk1MzY0OX0.wFCYP29g-QIesoM6Ai5qJB8fn22h19_64IhSYU0gN9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
